In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=100

In [5]:
one_hot_rpr = [one_hot(words,voc_size) for words in sent]
one_hot_rpr

[[87, 36, 25, 58],
 [87, 36, 25, 34],
 [87, 10, 25, 19],
 [76, 21, 30, 79, 25],
 [76, 21, 30, 79, 65],
 [73, 87, 14, 25, 70],
 [39, 19, 82, 79]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rpr,padding='pre',maxlen=sent_length)
embedded_docs

array([[ 0,  0,  0,  0, 87, 36, 25, 58],
       [ 0,  0,  0,  0, 87, 36, 25, 34],
       [ 0,  0,  0,  0, 87, 10, 25, 19],
       [ 0,  0,  0, 76, 21, 30, 79, 25],
       [ 0,  0,  0, 76, 21, 30, 79, 65],
       [ 0,  0,  0, 73, 87, 14, 25, 70],
       [ 0,  0,  0,  0, 39, 19, 82, 79]], dtype=int32)

In [9]:
dim=10


In [10]:
model=Sequential()
#model.add(Embedding(voc_size,dim,input_length=sent_length))
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_shape=(sent_length,)))
model.compile('adam','mse')

c:\Users\Shruti\Python Practice Folder\Udemy_GenAI\venv\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │         1,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,000 (3.91 KB)

 Trainable params: 1,000 (3.91 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step


array([[[-0.02235712, -0.04130381, -0.0205447 , -0.01778395,
          0.00759864,  0.00869515, -0.04694579,  0.03056763,
          0.01182168, -0.03033757],
        [-0.02235712, -0.04130381, -0.0205447 , -0.01778395,
          0.00759864,  0.00869515, -0.04694579,  0.03056763,
          0.01182168, -0.03033757],
        [-0.02235712, -0.04130381, -0.0205447 , -0.01778395,
          0.00759864,  0.00869515, -0.04694579,  0.03056763,
          0.01182168, -0.03033757],
        [-0.02235712, -0.04130381, -0.0205447 , -0.01778395,
          0.00759864,  0.00869515, -0.04694579,  0.03056763,
          0.01182168, -0.03033757],
        [-0.03034936, -0.00326556, -0.04614586, -0.02038895,
         -0.047387  ,  0.00588362, -0.04083035,  0.01164311,
          0.01697223, -0.04257982],
        [ 0.03380034,  0.02434209,  0.00950378, -0.01307186,
         -0.04147602, -0.01863839, -0.00714685, -0.02663933,
         -0.01017357,  0.02913583],
        [ 0.01294697, -0.0409859 ,  0.04423281,  0.0

In [13]:
embedded_docs[0]

array([ 0,  0,  0,  0, 87, 36, 25, 58], dtype=int32)

In [14]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None